### PR TITLE
reduce to core scientific package

### PR DESCRIPTION
**Pull request by bgotthold-usgs**
Moved the non 'usnvc' logic out of usnvc.py and into the example scripts. Made clear by linking documentation that the bis_pipeline.py script is not part of the  core usnvc process.

### CODE REVIEW

**Comment by skybristol** [comment]
I do want to clarify one fairly major point. @bgotthold-usgs you made this statement in a comment to the previous pull request:

"...when scientists make a new pipeline..."

I think you may be misunderstanding what I'm trying to achieve with all this stuff. For at least the foreseeable future, I do not anticipate anyone out side of our immediate group making new pipelines to process data through onto this part of live infrastructure (RDS-PG, DynamoDB, Elasticsearch, etc. with custom REST API routes). We don't need for all of the code to compose a particular data processing workflow to be in the same repo, expecting that the originator of the data integration idea is going to be carrying it through to production. It's a back and forth to get there.

The core principle that is at the heart of what I'm trying to do here is one of transparency and a degree of reproducibility. We need to be able to point at all of the codes that generate the data behind any of our API responses. Those codes need to be understandable enough so that reviewers are able to work through what we did and comment critically when we run this stuff through USGS Fundamental Science Practices. End users of the data products need to be able to trace back through what we did if they come up with questions and what's in the data. Wherever possible, our codes should be solid and well composed enough so that someone else can come along and build something new from them.

Does that make sense? Does it help to clarify what I'm after here?

**Comment by bgotthold-usgs** [comment]
@skybristol Yes, that makes sense. My point about "scientists making a new pipeline." was a bit premature. My understanding is as follows:
Like we are doing here for usnvc and are about to do for sgcn we (scientists and developers together) would take or create a scientific package, iterate on it and produce it in a way that is useful to ANYONE running on ANY infrastructure. When the package looks good, a developer can produce a simple script (bis_pipeline.py in this case) that allows the scientific package to be run on our infrastructure. During this process, we would work with the originator or SME  to be sure we are capturing the appropriate prov aspects. When this is in place, we can run the pipeline, produce a result, index it and provide the step by step prov trail for every piece of data produced.

**Comment by bgotthold-usgs** [comment]
@skybristol should we merge this in? (i don't have write access to this repo)

**Comment by skybristol** [comment]
@bgotthold-usgs I would characterize things in a different way that what you laid out.

Scientists today, both those on my team and others, do lots of data integration and prep work all the time. Sometimes this is geared toward producing a new data product of some kind, and other times it is in direct support of an analytical pursuit. My team is promoting doing this sort of work completely in code with end to end workflows that a) do the data wrangling job more clearly and efficiently, b) create a clear provenance trace between source data and analyzed data and c) create building blocks for others to use. We are trying to all amp up our game on software engineering so that we are producing functional/modular code rather than stream of consciousness scripts.

That all lives and happens completely independently of putting data into online cyberinfrastructure like we are doing here. Right now, if a scientist wants to get their data online, they can do so in a variety of ways. They can create a geospatial file form of the data and load it to ScienceBase to get Geoserver or ArcGIS services. They can load it to Amazon S3 and get some other functionality there. We're working on building other services on top of the ScienceBase Repository that work in similar fashion to Geoserver/ArcGIS (THREDDS and ERDDAP on the near horizon).

In the case of USNVC and SGCN (as well as some others we need to tackle next), we are essentially creating an optimized form of data that are integrated together and augmented with additional material. End targets in all of these cases so far are document/JSON data structures that are served well with Elasticsearch. We are building data distribution APIs that front the ES infrastructure and are tuned to answer specific questions and serve an audience that wants to build apps that tie into specific parts of these data structures in a live, online way.

Right now, we are building this. By we, I mean my team and yours. At this stage, we're not trying to build it in a way that anyone can write their own pipeline in future. What we are trying to do is make sure that our pipelines can directly use the basic functional code that was developed by scientists in that first stage. Right now, in our evolution, that means that really good software engineers like you need to also contribute to those foundational code projects as you try to use them in instantiating a pipeline into online data infrastructure. That helps give you a product you can work with and helps the original author of those codes hone their craft.

I'll take a look at your latest commits, but I think that the bis_pipeline stuff still needs to be pulled out of the pyusnvc package. We need to make sure the pyusnvc package can take the inputs it needs to and provide the outputs necessary to hand off into the pipeline, but the pipeline itself is a separate thing that needs to carry on independently.

**Comment by bgotthold-usgs** [comment]
@skybristol thanks for the response. Are you free sometime to talk about this. It would be great to have another call in the near future.

**Comment by skybristol** [comment]
Sure. I have time to talk this afternoon if you want. Let me know via chat and I'll set up a video deal.

**Comment by skybristol** [comment]
I'll merge this to develop and then work on some different terminology for the process to compose the workflow. I'll also work in a process to build a JSON schema for the unit documents.

**Pull request merged**
