### PR TITLE
pyusnvc changes for use in bis pipeline

### PR DESCRIPTION
**Pull request by bgotthold-usgs**
I tried to make the minimum number of changes in order to run this via the bis pipeline on aws. The biggest 'change' to the usnvc script that Sky wrote was splitting downloading the file from SB and connecting to the db file. The bis pipeline abstracts this process so it is not necessary to implement every time. The second change was to create the process.py file where we use the compatible method signatures to wrap the fundamental unsvc logic.

### CODE REVIEW

**Comment by bgotthold-usgs** [comment]
@aulenbac @mattaschmann

**Comment by skybristol** [comment]
Thanks @bgotthold-usgs for working through how to make this work within the processing framework you all have set up. I wasn't quite sure how best to handle the caching of the source data file for the target environment. Changes mostly make sense in your commits. I'm not sure what's up with BIS_PIPELINE_README.md, though. It looks like some stuff in there that doesn't apply to the USNVC use case in terms of schema validation.

**Comment by bgotthold-usgs** [comment]
@skybristol the BIS_PIPELINE_README.md file is basically the how to make a pipeline document at this point. Im fine with putting it somewhere else but i want to make sure when scientists make a new pipeline or make changes to an existing pipeline that they are aware of the documentation and can create their scripts in a way that needs minimum (hopefully none in the future) developer interaction. That schema validation in your example above is being actively applied when calling the send_final_result() function in process.py.

Something else to note. The creator of the package is free to include whatever they want for local use but things like elastic search, parallelization, downloading and unzipping from sciencebase are all being handled, with the hopes of reducing the responsibility of the creator to only the core scientific functionality. 

Here is a link to the live (beta) data produced by this script https://vpc-bcb-elasticsearch-6465hlavaogxyom2nsuozai7qu.us-west-2.es.amazonaws.com/bis_pipeline__pipeline_result__usnvc/_search

**Comment by skybristol** [comment]
We need to separate concerns a little bit and maybe further modularize the processing workflow, possibly breaking common pieces away from this package to some other tool(s).

The db_connection() function in my original was perhaps too specific and should have been broken out into two parts, both of which could maybe live in another package or packages to be called in here, whether deploying this to lambdas or running locally. Should we, perhaps, write one function to check a configurable locale for a source file or files and then hit ScienceBase with an HTTP download request to get the file(s) if necessary? That might even be an additional feature added to the sciencebasepy package. If we put in an optional check on the download_file() function from SbSession to take a couple of configurable actions (e.g., if "local_filename" file exists already then ignore or check date time and update), that could take care of that part of things.

Then we'd need another function somewhere to create different kinds of data connections to files. I'm not sure exactly where that should live, but maybe it doesn't need to live in pyusnvc. For expedience now, we could leave it there but split it out logically as something we want to migrate elsewhere in future.

The same would hold for parallelization where it seems like we ultimately need a set of generalized functions/classes that handle things like taking inputs and queuing messages. The message contents and strategies for breaking things up is going to be a bit different for every case, but the basic principles and processing logic seem like they should apply throughout.

If I understand what you're doing with JSON Schema validation and some type of information store end point, that's also a nicely modular piece. I was just noticing that BIS_PIPELINE_README.md had references to a geospatial feature type of schema that I didn't think applied to this use case. You've got other documentation in there that doesn't seem to apply specifically to the USNVC case, and I'm just wondering if that should be in some other package. Did you create a JSONSchema document for the JSON document form of the USNVC units? If so, where does that live? If you did create that, thank you! That's kind of a big chore I was meaning to get around to. It might be that, for now, that schema should just live right here in the code repo as it is specific to this case. We will ultimately want to register those somewhere as part of a property registry project I'm working on, but for now, we will also want to get the subject matter experts to provide the descriptions and other details for humans to the schema documentation and they can do that with contributions to the repo.

The raw Elasticsearch output for the documents run through the processing pipeline looks great! Just like it's supposed to.

**Comment by skybristol** [comment]
It looks like in your process_2() function from process, you are firing cache_unit() with a new option to return a JSOS string rather than dumping a file to a path. Why not just use build_unit() for what you need and put in a format parameter that determine whether it should send back a Python dictionary object or a JSON serialization. I wasn't really sure how best the Lambda/SQS environment should handle the data under your architecture, but build_unit may really be the only function that we really need there.

Also, what are all of these in your processing functions:

ch_ledger, send_final_result, send_to_stage, previous_stage_result

I can somewhat guess, but I'm not quite connecting the dots.

**Comment by bgotthold-usgs** [comment]
I agree with all of this. If you would like i can get started on generalizing this out a bit more while keeping the core 'usnvc' logic exactly as you have written.  

> lso, what are all of these in your processing functions:
ch_ledger, send_final_result, send_to_stage, previous_stage_result
I can somewhat guess, but I'm not quite connecting the dots.

that is exactly what  BIS_PIPELINE_README.md describes! those are the generalized methods for putting things on queues saving results, logging providence ect.  For example send_to_stage sends the message via sqs queue to process_2 which is running in its own lambda. send_final_result means that the record is finished all stages and ready to be saved in the database. 

> but build_unit may really be the only function that we really need there.

I think i understand and agree with this part.

**Pull request closed without merging**
